_name_or_path:
    value: Qwen/Qwen2.5-3B-Instruct
_wandb:
    value:
        cli_version: 0.26.0
        e:
            okltcu0z311e5po0lsv69hdhmzw8x28x:
                args:
                    - --train_data
                    - /home/zl3466/Documents/cmu/18786/proj/18786-project/data/train_sql_skeleton.jsonl
                    - --output_dir
                    - ./qwen3b-lora-adapter-skeleton
                    - --model_name
                    - Qwen/Qwen2.5-3B-Instruct
                    - --run_name
                    - qwen3b-sql-baseline-3000
                    - --max_steps
                    - "3000"
                codePath: qwen_lora_finetune.py
                codePathLocal: qwen_lora_finetune.py
                cpu_count: 16
                cpu_count_logical: 24
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "125389357056"
                        used: "71528448000"
                email: zl3466@nyu.edu
                executable: /home/zl3466/anaconda3/envs/sql/bin/python
                git:
                    commit: 36706ba5e5314091a0c65f13fcbcce4bd3b3301f
                    remote: https://github.com/Barr1x/18786-project.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-f93bd6b3-9094-96c0-fa9f-f24b0f4ff1d2
                host: zhiheng-ROG
                memory:
                    total: "67222478848"
                os: Linux-6.8.0-107-generic-x86_64-with-glibc2.35
                program: /home/zl3466/Documents/cmu/18786/proj/18786-project/qwen_lora_finetune.py
                python: CPython 3.10.20
                root: /home/zl3466/Documents/cmu/18786/proj/18786-project
                startedAt: "2026-04-19T00:34:22.819059Z"
                writerId: okltcu0z311e5po0lsv69hdhmzw8x28x
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 71
                - 84
                - 98
            "2":
                - 1
                - 11
                - 49
                - 51
                - 71
                - 84
                - 98
            "3":
                - 7
                - 13
                - 19
                - 66
            "4": 3.10.20
            "5": 0.26.0
            "6": 5.5.4
            "9":
                "1": transformers_trainer
            "12": 0.26.0
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
activation_offloading:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
architectures:
    value:
        - Qwen2ForCausalLM
assistant_only_loss:
    value: false
attention_dropout:
    value: 0
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: true
batch_eval_metrics:
    value: false
bf16:
    value: false
bf16_full_eval:
    value: false
bos_token_id:
    value: null
chat_template_path:
    value: null
chunk_size_feed_forward:
    value: 0
completion_only_loss:
    value: null
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
dataset_kwargs:
    value: null
dataset_num_proc:
    value: null
dataset_text_field:
    value: text
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
deepspeed:
    value: null
disable_tqdm:
    value: false
do_eval:
    value: false
do_predict:
    value: false
do_train:
    value: false
dtype:
    value: float32
enable_jit_checkpoint:
    value: false
eos_token:
    value: <EOS_TOKEN>
eos_token_id:
    value: 151645
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_packing:
    value: null
eval_steps:
    value: null
eval_strategy:
    value: "no"
eval_use_gather_object:
    value: false
fp16:
    value: true
fp16_full_eval:
    value: false
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
full_determinism:
    value: false
gradient_accumulation_steps:
    value: 8
gradient_checkpointing:
    value: true
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: null
hidden_act:
    value: silu
hidden_size:
    value: 2048
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: null
hub_revision:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_for_metrics:
    value: []
include_num_input_tokens_seen:
    value: "no"
initializer_range:
    value: 0.02
intermediate_size:
    value: 11008
is_encoder_decoder:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
layer_types:
    value:
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
learning_rate:
    value: 0.0002
length_column_name:
    value: length
liger_kernel_config:
    value: null
load_best_model_at_end:
    value: false
local_rank:
    value: -1
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: null
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 10
logging_strategy:
    value: steps
loss_type:
    value: nll
lr_scheduler_kwargs:
    value: null
lr_scheduler_type:
    value: cosine
max_grad_norm:
    value: 0.3
max_length:
    value: 2048
max_position_embeddings:
    value: 32768
max_steps:
    value: 3000
max_window_layers:
    value: 70
metric_for_best_model:
    value: null
model/num_parameters:
    value: 3205672960
model_init_kwargs:
    value: null
model_type:
    value: qwen2
neftune_noise_alpha:
    value: null
num_attention_heads:
    value: 16
num_hidden_layers:
    value: 36
num_key_value_heads:
    value: 2
num_train_epochs:
    value: 3
optim:
    value: paged_adamw_32bit
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: ./qwen3b-lora-adapter-skeleton
output_hidden_states:
    value: false
packing:
    value: false
packing_strategy:
    value: bfd
pad_to_multiple_of:
    value: null
pad_token:
    value: <PAD_TOKEN>
pad_token_id:
    value: 151643
padding_free:
    value: false
parallelism_config:
    value: null
peft_config:
    value:
        default:
            auto_mapping: null
            base_model_name_or_path: Qwen/Qwen2.5-3B-Instruct
            bias: none
            fan_in_fan_out: false
            inference_mode: false
            init_lora_weights: true
            layer_replication: null
            layers_pattern: null
            layers_to_transform: null
            lora_alpha: 32
            lora_dropout: 0.1
            megatron_config: null
            megatron_core: megatron.core
            modules_to_save: null
            peft_type: LORA
            r: 64
            revision: null
            target_modules:
                - gate_proj
                - down_proj
                - k_proj
                - o_proj
                - q_proj
                - v_proj
                - up_proj
            task_type: CAUSAL_LM
            use_dora: false
            use_rslora: false
per_device_eval_batch_size:
    value: 8
per_device_train_batch_size:
    value: 2
prediction_loss_only:
    value: false
problem_type:
    value: null
project:
    value: huggingface
push_to_hub:
    value: false
remove_unused_columns:
    value: true
report_to:
    value:
        - tensorboard
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
rms_norm_eps:
    value: 1e-06
rope_parameters:
    value:
        rope_theta: 1e+06
        rope_type: default
run_name:
    value: qwen3b-sql-baseline-3000
save_on_each_node:
    value: false
save_only_model:
    value: false
save_steps:
    value: 500
save_strategy:
    value: steps
save_total_limit:
    value: 3
seed:
    value: 42
shuffle_dataset:
    value: false
skip_memory_metrics:
    value: true
sliding_window:
    value: null
tf32:
    value: null
tie_word_embeddings:
    value: true
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_empty_cache_steps:
    value: null
trackio_space_id:
    value: trackio
train_sampling_strategy:
    value: random
transformers_version:
    value: 5.5.4
truncation_mode:
    value: keep_start
use_cache:
    value: false
use_cpu:
    value: false
use_liger_kernel:
    value: false
use_sliding_window:
    value: false
vocab_size:
    value: 151936
warmup_ratio:
    value: 0.1
warmup_steps:
    value: 0.1
weight_decay:
    value: 0
