_name_or_path:
    value: Qwen/Qwen2.5-3B-Instruct
_wandb:
    value:
        cli_version: 0.26.0
        e:
            takjn2kixloodwpwkbkmzae46zlc0tyy:
                args:
                    - --train_data
                    - data/train_sql.jsonl
                    - --model_name
                    - Qwen/Qwen2.5-3B-Instruct
                    - --output_dir
                    - ./qwen3b-lora-adapter-base
                    - --wandb_entity
                    - zl3466-new-york-university
                    - --wandb_project
                    - 18786_text2sql
                    - --run_name
                    - qwen3b-sql-base-3000
                    - --max_steps
                    - "3000"
                codePath: train/qwen_lora_finetune.py
                codePathLocal: train/qwen_lora_finetune.py
                cpu_count: 16
                cpu_count_logical: 24
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "125389357056"
                        used: "71554605056"
                email: zl3466@nyu.edu
                executable: /home/zl3466/anaconda3/envs/sql/bin/python
                git:
                    commit: a6fec1e31c5aee24e544c8f0e5662f6d7a60eb2d
                    remote: https://github.com/Barr1x/18786-project.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-f93bd6b3-9094-96c0-fa9f-f24b0f4ff1d2
                host: zhiheng-ROG
                memory:
                    total: "67222491136"
                os: Linux-6.8.0-107-generic-x86_64-with-glibc2.35
                program: /home/zl3466/Documents/cmu/18786/proj/18786-project/train/qwen_lora_finetune.py
                python: CPython 3.10.20
                root: /home/zl3466/Documents/cmu/18786/proj/18786-project
                startedAt: "2026-04-19T15:50:32.370107Z"
                writerId: takjn2kixloodwpwkbkmzae46zlc0tyy
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 71
                - 84
                - 98
            "2":
                - 1
                - 11
                - 49
                - 51
                - 71
                - 84
                - 98
            "3":
                - 7
                - 13
                - 19
                - 66
            "4": 3.10.20
            "5": 0.26.0
            "6": 4.57.6
            "9":
                "1": transformers_trainer
            "12": 0.26.0
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
architectures:
    value:
        - Qwen2ForCausalLM
attention_dropout:
    value: 0
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: true
bad_words_ids:
    value: null
batch_eval_metrics:
    value: false
begin_suppress_tokens:
    value: null
bf16:
    value: false
bf16_full_eval:
    value: false
bos_token_id:
    value: null
chunk_size_feed_forward:
    value: 0
cross_attention_hidden_size:
    value: null
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
decoder_start_token_id:
    value: null
deepspeed:
    value: null
disable_tqdm:
    value: false
diversity_penalty:
    value: 0
do_eval:
    value: false
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
dtype:
    value: float16
early_stopping:
    value: false
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: 151645
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: null
eval_strategy:
    value: "no"
eval_use_gather_object:
    value: false
exponential_decay_length_penalty:
    value: null
finetuning_task:
    value: null
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: true
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: null
full_determinism:
    value: false
gradient_accumulation_steps:
    value: 8
gradient_checkpointing:
    value: false
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: null
group_by_length:
    value: true
half_precision_backend:
    value: auto
hidden_act:
    value: silu
hidden_size:
    value: 2048
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: null
hub_revision:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_for_metrics:
    value: []
include_inputs_for_metrics:
    value: false
include_num_input_tokens_seen:
    value: "no"
include_tokens_per_second:
    value: false
initializer_range:
    value: 0.02
intermediate_size:
    value: 11008
is_decoder:
    value: false
is_encoder_decoder:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
layer_types:
    value:
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
learning_rate:
    value: 0.0002
length_column_name:
    value: length
length_penalty:
    value: 1
liger_kernel_config:
    value: null
load_best_model_at_end:
    value: false
local_rank:
    value: 0
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: ./qwen3b-lora-adapter-base/runs/Apr19_11-50-30_zhiheng-ROG
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 10
logging_strategy:
    value: steps
lr_scheduler_kwargs:
    value: null
lr_scheduler_type:
    value: cosine
max_grad_norm:
    value: 0.3
max_length:
    value: 20
max_position_embeddings:
    value: 32768
max_steps:
    value: 3000
max_window_layers:
    value: 70
metric_for_best_model:
    value: null
min_length:
    value: 0
model/num_parameters:
    value: 3205672960
model_type:
    value: qwen2
mp_parameters:
    value: ""
neftune_noise_alpha:
    value: null
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_attention_heads:
    value: 16
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_hidden_layers:
    value: 36
num_key_value_heads:
    value: 2
num_return_sequences:
    value: 1
num_train_epochs:
    value: 3
optim:
    value: paged_adamw_32bit
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: ./qwen3b-lora-adapter-base
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: false
pad_token_id:
    value: 151643
parallelism_config:
    value: null
past_index:
    value: -1
peft_config:
    value:
        default:
            auto_mapping: null
            base_model_name_or_path: Qwen/Qwen2.5-3B-Instruct
            bias: none
            fan_in_fan_out: false
            inference_mode: false
            init_lora_weights: true
            layer_replication: null
            layers_pattern: null
            layers_to_transform: null
            lora_alpha: 32
            lora_dropout: 0.1
            megatron_config: null
            megatron_core: megatron.core
            modules_to_save: null
            peft_type: LORA
            r: 64
            revision: null
            target_modules:
                - k_proj
                - up_proj
                - o_proj
                - down_proj
                - v_proj
                - gate_proj
                - q_proj
            task_type: CAUSAL_LM
            use_dora: false
            use_rslora: false
per_device_eval_batch_size:
    value: 8
per_device_train_batch_size:
    value: 2
per_gpu_eval_batch_size:
    value: null
per_gpu_train_batch_size:
    value: null
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: null
project:
    value: huggingface
push_to_hub:
    value: false
push_to_hub_model_id:
    value: null
push_to_hub_organization:
    value: null
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
ray_scope:
    value: last
remove_invalid_values:
    value: false
remove_unused_columns:
    value: true
repetition_penalty:
    value: 1
report_to:
    value:
        - tensorboard
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
return_dict_in_generate:
    value: false
rms_norm_eps:
    value: 1e-06
rope_scaling:
    value: null
rope_theta:
    value: 1e+06
run_name:
    value: qwen3b-sql-base-3000
save_on_each_node:
    value: false
save_only_model:
    value: false
save_safetensors:
    value: true
save_steps:
    value: 500
save_strategy:
    value: steps
save_total_limit:
    value: 3
seed:
    value: 42
sep_token_id:
    value: null
skip_memory_metrics:
    value: true
sliding_window:
    value: null
suppress_tokens:
    value: null
task_specific_params:
    value: null
temperature:
    value: 1
tf_legacy_loss:
    value: false
tf32:
    value: null
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: true
tokenizer_class:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_empty_cache_steps:
    value: null
torchdynamo:
    value: null
torchscript:
    value: false
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: null
trackio_space_id:
    value: trackio
transformers_version:
    value: 4.57.6
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cache:
    value: false
use_cpu:
    value: false
use_legacy_prediction_loop:
    value: false
use_liger_kernel:
    value: false
use_mps_device:
    value: false
use_sliding_window:
    value: false
vocab_size:
    value: 151936
warmup_ratio:
    value: 0.1
warmup_steps:
    value: 0
weight_decay:
    value: 0
